### ISSUE TITLE
OpenGL context not available

### ISSUE THREAD

**Issue by volkerrichert** [utensils/docker-opengl#1]
I try to run note ffmpeg-concat with transitions on top of this image. i did

- use this image as base
- add node support by using official node dockerfile
- add my node.js

all mp4 will be converted into raw, but applying transition will result in "failed to create OpenGL context".

I try to find the reason, but i can't find any GLX-extension loaded by XvFB.

xdpyinfo just displays the following extensions:

```
number of extensions:    22
    BIG-REQUESTS
    Composite
    DAMAGE
    DOUBLE-BUFFER
    Generic Event Extension
    MIT-SCREEN-SAVER
    MIT-SHM
    Present
    RANDR
    RECORD
    RENDER
    SECURITY
    SHAPE
    SYNC
    X-Resource
    XC-MISC
    XFIXES
    XINERAMA
    XInputExtension
    XKEYBOARD
    XTEST
    XVideo
```

Any Ideas?

THX, Volker

**Comment by jamesbrink** [comment]
@volkerrichert sorry for the extremely late response, did you figure this out? Looking at the package I see the same results. I found a few bug reports regarding this, but I suspect we may have something either misconfigured, or we might need to possibly build Xvfb from source. There is also an alternative option of using  Xdummy, but I think I would rather resolve this issue rather than just switching implementations.

**Comment by volkerrichert** [comment]
Puhhh.

i made millions of tests :-( 

One result was to switch to tini as entrypoint

```
ENTRYPOINT ["/usr/bin/tini", "--"]
```
XvFB waits for a signal which will be lost with the normal entrypoint because of missing parent process.

and i switched to buster-slim with the procompiled stuff. But it's not in production atm.
